name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run API Test
        id: run-newman
        uses: anthonyvsccode/newman-action@v1
        with:
          collection: collection.json
          reporters: cli

      - name: Output summary to console
        run: |
          # Add commands here to output a summary to the console
          echo "API test results summary:"
          # You can add more commands here to display relevant information
