name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # or any other command to install dependencies

      - name: Run tests
        run: npm test  # or any other command to run tests

      - name: Deploy
        if: success()  # Only deploy if previous steps succeed
        run: |
          # Commands to deploy to server
          # For example:
          # scp -r ./your-app user@your-server:/path/to/deployment
